// const graphdata = {
//   directed: false,
//   multigraph: false,
//   graph: {},
//   nodes: [
//     { id: "91", catagory: "C1" },
//     { id: "31", catagory: "C2" },
//     { id: "92", catagory: "C3" },
//     { id: "93", catagory: "C3" },
//     { id: "94", catagory: "C3" },
//     { id: "95", catagory: "C3" },
//     { id: "96", catagory: "C3" },
//     { id: "97", catagory: "C3" },
//     { id: "32", catagory: "C2" },
//     { id: "98", catagory: "C4" },
//     { id: "99", catagory: "C4" },
//     { id: "33", catagory: "C2" },
//   ],
//   links: [
//     { source: "91", target: "31", type: "D1" },
//     { source: "91", target: "32", type: "D1" },
//     { source: "91", target: "33", type: "D1" },
//     { source: "31", target: "92", type: "D2" },
//     { source: "31", target: "93", type: "D2" },
//     { source: "31", target: "94", type: "D2" },
//     { source: "31", target: "95", type: "D2" },
//     { source: "31", target: "96", type: "D2" },
//     { source: "31", target: "97", type: "D2" },
//     { source: "32", target: "98", type: "D3" },
//     { source: "32", target: "99", type: "D3" },
//   ],
// };

const gdata = {
  nodes: [
    { id: "Company A", catagory: "Managment" },
    { id: "Company B", catagory: "IT" },
    { id: "Company C", catagory: "Finance" },
    { id: "Employee 1", catagory: "Employee" },
    { id: "Branch 1", catagory: "Managment" },
    { id: "Employee 2", catagory: "Employee" },
    { id: "Branch 2", catagory: "IT" },
    { id: "Branch 3", catagory: "Finance" },
    { id: "Branch 4", catagory: "Finance" },
    { id: "Branch 5", catagory: "Managment" },
    { id: "Branch 6", catagory: "IT" },
    { id: "Branch 7", catagory: "IT" },
    { id: "Branch 8", catagory: "Managment" },
    { id: "Employee 3", catagory: "Employee" },
    { id: "Employee 4", catagory: "Employee" },
    { id: "Employee 5", catagory: "Employee" },
    { id: "Employee 6", catagory: "Employee" },
    { id: "Employee 7", catagory: "Employee" },
    { id: "Employee 8", catagory: "Employee" },
    { id: "Employee 9", catagory: "Employee" },
    { id: "Employee 10", catagory: "Employee" },
    { id: "Employee 11", catagory: "Employee" },
    { id: "Employee 12", catagory: "Employee" },
    { id: "Employee 13", catagory: "Employee" },
    { id: "Employee 14", catagory: "Employee" },
    { id: "Employee 15", catagory: "Employee" },
    { id: "Employee 16", catagory: "Employee" },
    { id: "Employee 17", catagory: "Employee" },
    { id: "Employee 18", catagory: "Employee" },
    { id: "Employee 19", catagory: "Employee" },
    { id: "Employee 20", catagory: "Employee" },
    { id: "Employee 21", catagory: "Employee" },
    { id: "Employee 22", catagory: "Employee" },
    { id: "Employee 23", catagory: "Employee" },
    { id: "Employee 24", catagory: "Employee" },
    { id: "Employee 25", catagory: "Employee" },
    { id: "Company D", catagory: "IT" },
    { id: "Company E", catagory: "IT" },
    { id: "Company G", catagory: "IT" },
  ],
  links: [
    {
      source: "Company A",
      target: "Company B",
      type: "work",
    },
    {
      source: "Company A",
      target: "Branch 2",
      type: "branch",
    },
    {
      source: "Company A",
      target: "Company C",
      type: "client",
    },
    {
      source: "Company A",
      target: "Employee 1",
      type: "employment",
    },
    {
      source: "Company A",
      target: "Employee 2",
      type: "employment",
    },
    {
      source: "Company A",
      target: "Employee 3",
      type: "employment",
    },
    {
      source: "Company A",
      target: "Branch 1",
      type: "branch",
    },
    {
      source: "Company B",
      target: "Employee 4",
      type: "employment",
    },
    {
      source: "Company B",
      target: "Employee 5",
      type: "employment",
    },
    {
      source: "Company B",
      target: "Branch 2",
      type: "client",
    },

    {
      source: "Company C",
      target: "Branch 3",
      type: "branch",
    },
    {
      source: "Company C",
      target: "Employee 7",
      type: "employment",
    },
    {
      source: "Company C",
      target: "Employee 8",
      type: "employment",
    },
    {
      source: "Company C",
      target: "Employee 9",
      type: "employment",
    },
    {
      source: "Company C",
      target: "Employee 10",
      type: "employment",
    },
    {
      source: "Company B",
      target: "Company D",
      type: "client",
    },
    {
      source: "Branch 1",
      target: "Employee 11",
      type: "employment",
    },
    {
      source: "Branch 1",
      target: "Employee 12",
      type: "employment",
    },
    {
      source: "Branch 2",
      target: "Employee 13",
      type: "employment",
    },
    {
      source: "Branch 2",
      target: "Employee 14",
      type: "employment",
    },
    {
      source: "Branch 2",
      target: "Employee 15",
      type: "employment",
    },
    {
      source: "Branch 3",
      target: "Company D",
      type: "client",
    },
    {
      source: "Branch 3",
      target: "Employee 16",
      type: "employment",
    },
    {
      source: "Branch 3",
      target: "Employee 17",
      type: "employment",
    },
    {
      source: "Branch 3",
      target: "Employee 18",
      type: "employment",
    },
    {
      source: "Company D",
      target: "Branch 4",
      type: "branch",
    },
    {
      source: "Company D",
      target: "Branch 5",
      type: "branch",
    },
    {
      source: "Company C",
      target: "Branch 6",
      type: "branch",
    },
    {
      source: "Company B",
      target: "Branch 7",
      type: "branch",
    },
    {
      source: "Company A",
      target: "Branch 8",
      type: "branch",
    },
    {
      source: "Branch 8",
      target: "Employee 6",
      type: "employment",
    },
    {
      source: "Branch 8",
      target: "Branch 4",
      type: "client",
    },
    {
      source: "Branch 7",
      target: "Employee 19",
      type: "employment",
    },
    {
      source: "Branch 7",
      target: "Employee 20",
      type: "employment",
    },
    {
      source: "Branch 6",
      target: "Employee 21",
      type: "employment",
    },
    {
      source: "Branch 6",
      target: "Employee 22",
      type: "employment",
    },
    {
      source: "Branch 5",
      target: "Employee 23",
      type: "employment",
    },
    {
      source: "Branch 5",
      target: "Employee 24",
      type: "employment",
    },
    {
      source: "Branch 4",
      target: "Employee 25",
      type: "employment",
    },
    {
      source: "Company E",
      target: "Company G",
      type: "client",
    },
    {
      source: "Company A",
      target: "Company G",
      type: "client",
    },
    {
      source: "Company A",
      target: "Company E",
      type: "work",
    },
  ],
};

export default gdata;
